-- M1: family data, typed references and household isolation.
create table public.households (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now());
create table public.parents (id uuid primary key references auth.users(id) on delete cascade, household_id uuid not null references public.households on delete cascade, display_name text not null default 'Forelder', unique(id, household_id));
create table public.learners (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households on delete cascade, first_name text not null check (length(first_name) between 1 and 40), grade int not null default 4 check (grade between 1 and 13), birth_year int, tutor_name text not null default 'Lumi', avatar text not null default 'ugle', settings jsonb not null default '{"session_minutes":15,"daily_max_minutes":30,"voice":false}', unique(id,household_id));
create table public.parent_secrets (parent_id uuid primary key references public.parents on delete cascade, pin_hash text not null, failed_attempts int not null default 0, locked_until timestamptz);
create table public.devices (id uuid primary key, household_id uuid not null, learner_id uuid not null, parent_id uuid not null, leo_mode_locked boolean not null default false, created_at timestamptz not null default now(), foreign key(learner_id,household_id) references public.learners(id,household_id) on delete cascade, foreign key(parent_id,household_id) references public.parents(id,household_id) on delete cascade);
create table public.subjects (id text primary key, title text not null);
create table public.medallion_parts (id int not null check (id between 1 and 4), subject_id text not null references public.subjects, grade int not null, title text not null, description text not null, symbol text not null, color text not null, primary key(subject_id,grade,id));
create table public.skills (id text primary key, subject_id text not null references public.subjects, title text not null, description text not null, lk20_aim_code text not null, lk20_aim_text text not null, grade int not null, medallion_part int, prerequisites text[] not null default '{}', generator_key text not null, difficulty_levels int not null default 5 check(difficulty_levels=5), order_index int not null, foreign key(subject_id,grade,medallion_part) references public.medallion_parts(subject_id,grade,id));
create table public.sessions (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, started_at timestamptz not null default now(), ended_at timestamptz, planned_minutes int not null default 15 check(planned_minutes between 1 and 60), mood_start text, mood_end text, wanted_more bool, summary text, stats jsonb not null default '{}', unique(id,learner_id));
create table public.interests (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, label text not null, source text not null check(source in ('leo','forelder','foreslått')), weight float not null default 1, active bool not null default true, times_used int not null default 0, engagement_avg float, unique(id,learner_id));
create table public.items (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, skill_id text not null references public.skills, origin text not null check(origin in ('generator','modell')), difficulty int not null check(difficulty between 1 and 5), params jsonb not null, answer jsonb not null, expression text, representation text, strategy jsonb, interest_id uuid, story_text text, visual_spec jsonb, prompt_version text, validated bool not null default false, reused_count int not null default 0, unique(id,learner_id), foreign key(interest_id,learner_id) references public.interests(id,learner_id));
create table public.attempts (id uuid primary key default gen_random_uuid(), session_id uuid not null, item_id uuid not null, learner_id uuid not null references public.learners on delete cascade, answer_raw text, answer_parsed jsonb, correct bool not null, credit float not null check(credit between 0 and 1), hint_level_used int not null check(hint_level_used between 0 and 4), time_ms int not null check(time_ms>=0), input_mode text not null check(input_mode in ('tastatur','tale','manipulativ')), misconception_code text, explanation_text text, explanation_score jsonb, is_master_test bool not null default false, created_at timestamptz not null default now(), foreign key(session_id,learner_id) references public.sessions(id,learner_id) on delete cascade, foreign key(item_id,learner_id) references public.items(id,learner_id) on delete cascade);
create table public.messages (id uuid primary key default gen_random_uuid(), session_id uuid not null, learner_id uuid not null references public.learners on delete cascade, role text not null check(role in ('leo','lærer','system')), text text not null, meta jsonb not null default '{}', created_at timestamptz not null default now(), foreign key(session_id,learner_id) references public.sessions(id,learner_id) on delete cascade, unique(id,session_id,learner_id));
create table public.tool_calls (id uuid primary key default gen_random_uuid(), session_id uuid not null, learner_id uuid not null references public.learners on delete cascade, message_id uuid, tool text not null, args jsonb not null, result jsonb, ok bool not null, latency_ms int, created_at timestamptz not null default now(), foreign key(session_id,learner_id) references public.sessions(id,learner_id) on delete cascade, foreign key(message_id,session_id,learner_id) references public.messages(id,session_id,learner_id) on delete cascade);
create table public.skill_states (learner_id uuid not null references public.learners on delete cascade, skill_id text not null references public.skills, theta float not null default 0, attempts int not null default 0, correct_no_hint int not null default 0, distinct_days_correct int not null default 0, recent_attempts jsonb not null default '[]', model_mastery_claim_at timestamptz, mastered_at timestamptz, fsrs_card jsonb, next_review_at timestamptz, last_seen_at timestamptz, primary key(learner_id,skill_id));
create table public.medallion_progress (learner_id uuid not null references public.learners on delete cascade, part_id int not null, subject_id text not null default 'matte', grade int not null default 4, status text not null default 'låst' check(status in ('låst','tilgjengelig','pågår','klar_for_mesterprøve','tildelt')), skills_mastered int not null default 0, skills_total int not null, master_test_attempts int not null default 0, awarded_at timestamptz, parent_seen bool not null default false, primary key(learner_id,subject_id,grade,part_id), foreign key(subject_id,grade,part_id) references public.medallion_parts(subject_id,grade,id));
create table public.master_tests (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, part_id int not null, subject_id text not null default 'matte', grade int not null default 4, session_id uuid not null, item_ids uuid[] not null, score float check(score between 0 and 1), passed bool, created_at timestamptz not null default now(), foreign key(session_id,learner_id) references public.sessions(id,learner_id) on delete cascade, foreign key(subject_id,grade,part_id) references public.medallion_parts(subject_id,grade,id));
create table public.school_topics (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, raw_text text not null, mapped_skill_ids text[] not null, confidence float not null check(confidence between 0 and 1), expires_at timestamptz not null default now()+interval '7 days', created_at timestamptz not null default now());
create table public.misconceptions (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, skill_id text not null references public.skills, code text not null, description text not null, evidence_count int not null default 1, last_seen_at timestamptz not null default now(), status text not null default 'aktiv' check(status in ('aktiv','løst')), unique(learner_id,skill_id,code));
create table public.learner_profile_observations (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, category text not null check(category in ('interesse','læringspreferanse','motivasjon','styrke','utfordring','misoppfatning','skolemetode')), text text not null, evidence jsonb not null default '{}', confidence float not null default 0.4 check(confidence between 0 and 1), status text not null default 'aktiv' check(status in ('aktiv','låst','avvist')), updated_by text not null check(updated_by in ('system','forelder')), updated_at timestamptz not null default now());
create table public.strategy_arms (learner_id uuid not null references public.learners on delete cascade, dimension text not null, arm text not null, alpha float not null default 1 check(alpha>0), beta float not null default 1 check(beta>0), pulls int not null default 0, updated_at timestamptz not null default now(), primary key(learner_id,dimension,arm));
create table public.safety_flags (id uuid primary key default gen_random_uuid(), learner_id uuid not null references public.learners on delete cascade, session_id uuid, type text not null, excerpt text, created_at timestamptz not null default now(), reviewed bool not null default false, foreign key(session_id,learner_id) references public.sessions(id,learner_id) on delete cascade);
create table public.ai_calls (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households on delete cascade, purpose text not null, model text not null, input_tokens int not null, output_tokens int not null, cost_estimate float not null, latency_ms int, ok bool not null, created_at timestamptz not null default now());
create table public.tts_cache (text_hash text not null, voice text not null, storage_path text not null, primary key(text_hash,voice));

-- SECURITY DEFINER helpers avoid recursive RLS on parents. Fixed search_path.
create function public.in_household(target uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.parents where id=(select auth.uid()) and household_id=target); $$;
create function public.owns_learner(target uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.learners l join public.parents p on p.household_id=l.household_id where p.id=(select auth.uid()) and l.id=target); $$;
revoke all on function public.in_household(uuid), public.owns_learner(uuid) from public;
grant execute on function public.in_household(uuid), public.owns_learner(uuid) to authenticated;

create function public.ensure_household() returns uuid language plpgsql security definer set search_path = '' as $$
declare h uuid;
begin
 if auth.uid() is null then raise exception 'Innlogging kreves'; end if;
 -- Serialize concurrent first logins for this user.
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text,0));
 select household_id into h from public.parents where id=auth.uid();
 if h is null then
  insert into public.households default values returning id into h;
  insert into public.parents(id,household_id) values(auth.uid(),h);
 end if;
 return h;
end; $$;
revoke all on function public.ensure_household() from public;
grant execute on function public.ensure_household() to authenticated;
alter table public.households enable row level security;
revoke all on public.households from anon, authenticated;
grant all on public.households to service_role;
grant select on public.households to authenticated;
create policy family_read on public.households for select to authenticated using (public.in_household(id));
alter table public.parents enable row level security;
revoke all on public.parents from anon, authenticated;
grant all on public.parents to service_role;
grant select on public.parents to authenticated;
create policy family_read on public.parents for select to authenticated using (public.in_household(household_id));
alter table public.learners enable row level security;
revoke all on public.learners from anon, authenticated;
grant all on public.learners to service_role;
grant select on public.learners to authenticated;
create policy family_read on public.learners for select to authenticated using (public.in_household(household_id));
grant insert, update, delete on public.learners to authenticated;
create policy family_write on public.learners for all to authenticated using (public.in_household(household_id)) with check (public.in_household(household_id));
alter table public.devices enable row level security;
revoke all on public.devices from anon, authenticated;
grant all on public.devices to service_role;
grant select on public.devices to authenticated;
create policy family_read on public.devices for select to authenticated using (parent_id=(select auth.uid()) and public.in_household(household_id));
alter table public.ai_calls enable row level security;
revoke all on public.ai_calls from anon, authenticated;
grant all on public.ai_calls to service_role;
grant select on public.ai_calls to authenticated;
create policy family_read on public.ai_calls for select to authenticated using (public.in_household(household_id));
alter table public.parent_secrets enable row level security;
revoke all on public.parent_secrets from anon, authenticated;
grant all on public.parent_secrets to service_role;
alter table public.tts_cache enable row level security;
revoke all on public.tts_cache from anon, authenticated;
grant all on public.tts_cache to service_role;
alter table public.subjects enable row level security;
revoke all on public.subjects from anon, authenticated;
grant all on public.subjects to service_role;
grant select on public.subjects to authenticated;
create policy reference_read on public.subjects for select to authenticated using (true);
alter table public.skills enable row level security;
revoke all on public.skills from anon, authenticated;
grant all on public.skills to service_role;
grant select on public.skills to authenticated;
create policy reference_read on public.skills for select to authenticated using (true);
alter table public.medallion_parts enable row level security;
revoke all on public.medallion_parts from anon, authenticated;
grant all on public.medallion_parts to service_role;
grant select on public.medallion_parts to authenticated;
create policy reference_read on public.medallion_parts for select to authenticated using (true);
alter table public.sessions enable row level security;
revoke all on public.sessions from anon, authenticated;
grant all on public.sessions to service_role;
grant select on public.sessions to authenticated;
create policy family_read on public.sessions for select to authenticated using (public.owns_learner(learner_id));
create index sessions_learner_idx on public.sessions(learner_id);
alter table public.interests enable row level security;
revoke all on public.interests from anon, authenticated;
grant all on public.interests to service_role;
grant select on public.interests to authenticated;
create policy family_read on public.interests for select to authenticated using (public.owns_learner(learner_id));
grant insert, update, delete on public.interests to authenticated;
create policy family_write on public.interests for all to authenticated using (public.owns_learner(learner_id)) with check (public.owns_learner(learner_id));
create index interests_learner_idx on public.interests(learner_id);
alter table public.items enable row level security;
revoke all on public.items from anon, authenticated;
grant all on public.items to service_role;
grant select on public.items to authenticated;
create policy family_read on public.items for select to authenticated using (public.owns_learner(learner_id));
create index items_learner_idx on public.items(learner_id);
alter table public.attempts enable row level security;
revoke all on public.attempts from anon, authenticated;
grant all on public.attempts to service_role;
grant select on public.attempts to authenticated;
create policy family_read on public.attempts for select to authenticated using (public.owns_learner(learner_id));
create index attempts_learner_idx on public.attempts(learner_id);
alter table public.messages enable row level security;
revoke all on public.messages from anon, authenticated;
grant all on public.messages to service_role;
grant select on public.messages to authenticated;
create policy family_read on public.messages for select to authenticated using (public.owns_learner(learner_id));
create index messages_learner_idx on public.messages(learner_id);
alter table public.tool_calls enable row level security;
revoke all on public.tool_calls from anon, authenticated;
grant all on public.tool_calls to service_role;
grant select on public.tool_calls to authenticated;
create policy family_read on public.tool_calls for select to authenticated using (public.owns_learner(learner_id));
create index tool_calls_learner_idx on public.tool_calls(learner_id);
alter table public.skill_states enable row level security;
revoke all on public.skill_states from anon, authenticated;
grant all on public.skill_states to service_role;
grant select on public.skill_states to authenticated;
create policy family_read on public.skill_states for select to authenticated using (public.owns_learner(learner_id));
create index skill_states_learner_idx on public.skill_states(learner_id);
alter table public.medallion_progress enable row level security;
revoke all on public.medallion_progress from anon, authenticated;
grant all on public.medallion_progress to service_role;
grant select on public.medallion_progress to authenticated;
create policy family_read on public.medallion_progress for select to authenticated using (public.owns_learner(learner_id));
create index medallion_progress_learner_idx on public.medallion_progress(learner_id);
alter table public.master_tests enable row level security;
revoke all on public.master_tests from anon, authenticated;
grant all on public.master_tests to service_role;
grant select on public.master_tests to authenticated;
create policy family_read on public.master_tests for select to authenticated using (public.owns_learner(learner_id));
create index master_tests_learner_idx on public.master_tests(learner_id);
alter table public.school_topics enable row level security;
revoke all on public.school_topics from anon, authenticated;
grant all on public.school_topics to service_role;
grant select on public.school_topics to authenticated;
create policy family_read on public.school_topics for select to authenticated using (public.owns_learner(learner_id));
create index school_topics_learner_idx on public.school_topics(learner_id);
alter table public.misconceptions enable row level security;
revoke all on public.misconceptions from anon, authenticated;
grant all on public.misconceptions to service_role;
grant select on public.misconceptions to authenticated;
create policy family_read on public.misconceptions for select to authenticated using (public.owns_learner(learner_id));
create index misconceptions_learner_idx on public.misconceptions(learner_id);
alter table public.learner_profile_observations enable row level security;
revoke all on public.learner_profile_observations from anon, authenticated;
grant all on public.learner_profile_observations to service_role;
grant select on public.learner_profile_observations to authenticated;
create policy family_read on public.learner_profile_observations for select to authenticated using (public.owns_learner(learner_id));
create index learner_profile_observations_learner_idx on public.learner_profile_observations(learner_id);
alter table public.strategy_arms enable row level security;
revoke all on public.strategy_arms from anon, authenticated;
grant all on public.strategy_arms to service_role;
grant select on public.strategy_arms to authenticated;
create policy family_read on public.strategy_arms for select to authenticated using (public.owns_learner(learner_id));
create index strategy_arms_learner_idx on public.strategy_arms(learner_id);
alter table public.safety_flags enable row level security;
revoke all on public.safety_flags from anon, authenticated;
grant all on public.safety_flags to service_role;
grant select on public.safety_flags to authenticated;
create policy family_read on public.safety_flags for select to authenticated using (public.owns_learner(learner_id));
create index safety_flags_learner_idx on public.safety_flags(learner_id);
create index parents_household_idx on public.parents(household_id);
create index learners_household_idx on public.learners(household_id);
create index devices_parent_idx on public.devices(parent_id);
-- Serialize PIN attempts; stale/concurrent verification cannot bypass lockout.
create function public.record_pin_attempt(target_parent uuid, success boolean) returns boolean language plpgsql security definer set search_path='' as $$
declare s public.parent_secrets;
begin
 select * into s from public.parent_secrets where parent_id=target_parent for update;
 if not found or s.locked_until>now() then return false; end if;
 if success then update public.parent_secrets set failed_attempts=0,locked_until=null where parent_id=target_parent; return true; end if;
 if s.locked_until is not null then s.failed_attempts:=0; end if;
 update public.parent_secrets set failed_attempts=s.failed_attempts+1, locked_until=case when s.failed_attempts+1>=5 then now()+interval '15 minutes' else null end where parent_id=target_parent;
 return false;
end; $$;
revoke all on function public.record_pin_attempt(uuid,boolean) from public,anon,authenticated;
grant execute on function public.record_pin_attempt(uuid,boolean) to service_role;
